<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Document;

class DocumentSeeder extends Seeder
{
    public function run()
    {
        $documents = [
            [
                'id' => 1,
                'nama' => 'KAK - Tes kegiatan fuad',
                'kategori' => 'Pengajuan Permintaan Pengadaan',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'Kerangka Ajuan Kerja',
                'path' => 'kak-file/KAK-Tes kegiatan fuad.pdf',
                'is_valid' => NULL,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 14,
                'created_at' => '2024-08-25 16:11:41',
                'updated_at' => '2024-08-25 16:11:41',
            ],
            [
                'id' => 2,
                'nama' => 'FP - Tes kegiatan fuad',
                'kategori' => 'Pengajuan Permintaan Pengadaan',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'Form Permintaan',
                'path' => 'fp-file/FP-Tes kegiatan fuad.pdf',
                'is_valid' => NULL,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 14,
                'created_at' => '2024-08-25 16:12:39',
                'updated_at' => '2024-08-25 16:12:39',
            ],
            [
                'id' => 3,
                'nama' => 'SP - Tes kegiatan fuad',
                'kategori' => 'Pengajuan Permintaan Pengadaan',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'Surat Permintaan',
                'path' => 'sp-file/SP-Tes kegiatan fuad.pdf',
                'is_valid' => NULL,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 14,
                'created_at' => '2024-08-25 16:12:39',
                'updated_at' => '2024-08-25 16:12:39',
            ],
            [
                'id' => 4,
                'nama' => 'RC - Tes kegiatan fuad',
                'kategori' => 'Pengajuan PBJ',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'Rancangan Kontrak',
                'path' => 'rc-file/RC-Tes kegiatan fuad.pdf',
                'is_valid' => NULL,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 27,
                'created_at' => '2024-08-25 16:19:13',
                'updated_at' => '2024-08-25 16:19:13',
            ],
            [
                'id' => 5,
                'nama' => 'SPEKTEKNIS - Tes kegiatan fuad',
                'kategori' => 'Pengajuan PBJ',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'Spekteknis',
                'path' => 'spekteknis-file/SPEKTEKNIS-Tes kegiatan fuad.pdf',
                'is_valid' => NULL,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 27,
                'created_at' => '2024-08-25 16:19:13',
                'updated_at' => '2024-08-25 16:19:13',
            ],
            [
                'id' => 6,
                'nama' => 'SPPBJ - Tes kegiatan fuad',
                'kategori' => 'Pengajuan Kontrak',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'Surat Penetapan Pemenang Barang dan Jasa(SPPBJ)',
                'path' => 'sppbj-file/SPPBJ-Tes kegiatan fuad.pdf',
                'is_valid' => NULL,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 26,
                'created_at' => '2024-08-25 16:50:27',
                'updated_at' => '2024-08-25 16:50:27',
            ],
            [
                'id' => 7,
                'nama' => 'SPM - Tes kegiatan fuad',
                'kategori' => 'Berkas Pembayaran',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'Surat Perintah Pembayaran(SPM)',
                'path' => 'spm-file/SPM-Tes kegiatan fuad.pdf',
                'is_valid' => 1,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 28,
                'created_at' => '2024-08-25 17:13:00',
                'updated_at' => '2024-08-27 01:44:02',
            ],
            [
                'id' => 8,
                'nama' => 'BAST - Tes kegiatan fuad',
                'kategori' => 'Pengajuan Berita Acara',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'Berita Acara Serah Terima(BAST)',
                'path' => 'bast-file/BAST-Tes kegiatan fuad.pdf',
                'is_valid' => NULL,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 27,
                'created_at' => '2024-08-26 08:41:28',
                'updated_at' => '2024-08-26 08:41:28',
            ],
            [
                'id' => 9,
                'nama' => 'SP - Tes kegiatan fuad',
                'kategori' => 'Pengajuan Kuitansi',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'Surat Pesanan',
                'path' => 'sp-file/SP-Tes kegiatan fuad.pdf',
                'is_valid' => 1,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 26,
                'created_at' => '2024-08-26 09:38:50',
                'updated_at' => '2024-08-27 01:44:18',
            ],
            [
                'id' => 10,
                'nama' => 'RAB - Tes kegiatan fuad',
                'kategori' => 'Pengajuan PBJ',
                'tipe_file' => 'pdf',
                'jenis_dokumen' => 'RAB/HPS',
                'path' => 'rab-file/RAB-Tes kegiatan fuad.pdf',
                'is_valid' => NULL,
                'konten' => NULL,
                'pengajuan_id' => 1,
                'submitted_by' => 27,
                'created_at' => '2024-08-27 01:19:31',
                'updated_at' => '2024-08-27 01:19:31',
            ],
        ];

        foreach ($documents as $document) {
            Document::create($document);
        }
    }
}
